# Generated by Django 5.0.3 on 2024-07-18 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMetadataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('basemetadatamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metadata.basemetadatamodel')),
            ],
            options={
                'db_table': 'countries',
            },
            bases=('metadata.basemetadatamodel',),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('basemetadatamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metadata.basemetadatamodel')),
            ],
            options={
                'db_table': 'genres',
            },
            bases=('metadata.basemetadatamodel',),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('basemetadatamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metadata.basemetadatamodel')),
                ('abbrevation', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'language',
            },
            bases=('metadata.basemetadatamodel',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('basemetadatamodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metadata.basemetadatamodel')),
            ],
            options={
                'db_table': 'tags',
            },
            bases=('metadata.basemetadatamodel',),
        ),
    ]
