# Generated by Django 5.0.3 on 2024-07-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='abbrevation',
            new_name='abbreviation',
        ),
    ]
