# Generated by Django 5.0.3 on 2024-09-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('team_type', models.CharField(choices=[('autor', 'Autor'), ('translator', 'Translator')], default='autor')),
                ('description', models.TextField(blank=True, null=True)),
                ('novels', models.ManyToManyField(blank=True, related_name='teams', to='novels.novel')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
