# Generated by Django 5.0.3 on 2024-07-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='novels',
            field=models.ManyToManyField(related_name='teams', to='novels.novel'),
        ),
    ]
