# Generated by Django 5.0.3 on 2024-08-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_novels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('autor', 'Autor'), ('translator', 'Translator')], default='autor'),
        ),
    ]
