# Generated by Django 5.0.3 on 2024-08-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_alter_novel_original_title'),
        ('teams', '0003_alter_team_team_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='novels',
            field=models.ManyToManyField(blank=True, related_name='teams', to='novels.novel'),
        ),
    ]
