# Generated by Django 5.0.3 on 2024-07-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_team_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.IntegerField(choices=[(2, 'Translator'), (1, 'Autor')], default=1),
        ),
    ]
