# Generated by Django 5.0.3 on 2024-07-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_team_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.IntegerField(choices=[(1, 'Autor'), (2, 'Translator')], default=1),
        ),
    ]
