# Generated by Django 5.0.3 on 2024-08-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to='users_avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.CharField(db_index=True, default=models.CharField(max_length=150, unique=True, verbose_name='user name'), max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='user name'),
        ),
    ]
