# Generated by Django 5.0.3 on 2024-08-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordreset_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='created',
            new_name='created_at',
        ),
    ]
