# Generated by Django 5.0.3 on 2024-07-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator_teams', '0002_rename_translatorteams_translatorteam'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='translatorteam',
            table='translator-teams',
        ),
    ]
