# Generated by Django 5.0.3 on 2024-08-28 16:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
        ('chapters', '0002_alter_chapter_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('chapter', 'user')},
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='novel',
        ),
    ]
