# Generated by Django 5.0.3 on 2024-07-04 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
        ('translator_teams', '0002_rename_translatorteams_translatorteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'default_related_name': 'chapters', 'ordering': ['novel', '-created_at', 'translator_team']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='translator_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='translator_teams.translatorteam'),
        ),
    ]
