# Generated by Django 5.0.3 on 2024-07-15 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
        ('teams', '__first__'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'default_related_name': 'chapters', 'ordering': ['novel', '-created_at', 'team']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
