# Generated by Django 5.0.3 on 2024-07-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'default_related_name': 'chapters', 'ordering': ['volume', 'number', 'team']},
        ),
    ]
