# Generated by Django 5.0.3 on 2024-07-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_alter_chapter_options_chapter_translator_team'),
        ('translator_teams', '0002_rename_translatorteams_translatorteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='translator_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translator_teams.translatorteam'),
        ),
    ]
