# Generated by Django 5.0.3 on 2024-07-18 13:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default=models.CharField(max_length=255), max_length=255)),
                ('original_title', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Continues'), (2, 'Finished'), (3, 'Frozen')], default=1)),
                ('synopsys', models.TextField(null=True)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.country')),
                ('genres', models.ManyToManyField(db_index=True, to='metadata.genre')),
                ('language', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='novels', to='metadata.language')),
                ('tags', models.ManyToManyField(db_index=True, to='metadata.tag')),
                ('translate_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translated_novels', to='metadata.language')),
            ],
            options={
                'db_table': 'novels',
                'ordering': ['-created_at'],
            },
        ),
    ]
