# Generated by Django 5.0.3 on 2024-09-11 12:22

import apps.novels.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('cover', models.ImageField(default='default_novel_cover.png', upload_to=apps.novels.models._get_image_save_path)),
                ('slug', models.SlugField(default=models.CharField(max_length=255, unique=True), max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('continues', 'Continues'), ('finished', 'Finished'), ('frozen', 'Frozen'), ('licensed', 'Licensed')], default='continues')),
                ('synopsys', models.TextField(null=True)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='metadata.country')),
            ],
            options={
                'db_table': 'novels',
                'ordering': ['-created_at'],
            },
        ),
    ]
