# Generated by Django 5.0.3 on 2024-09-11 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
        ('novels', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_novels', to='teams.team'),
        ),
        migrations.AddField(
            model_name='novel',
            name='genres',
            field=models.ManyToManyField(db_index=True, to='metadata.genre'),
        ),
        migrations.AddField(
            model_name='novel',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='novels', to='metadata.language'),
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(db_index=True, to='metadata.tag'),
        ),
        migrations.AddField(
            model_name='novel',
            name='translated_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translated_novels', to='metadata.language'),
        ),
    ]
