# Generated by Django 5.0.3 on 2024-08-13 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
        ('teams', '0002_alter_team_novels'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_novels', to='teams.team'),
        ),
    ]
