# Generated by Django 5.0.3 on 2024-08-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_novel_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='translate_language',
            new_name='translated_language',
        ),
    ]
