# Generated by Django 5.0.2 on 2024-02-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_alter_novel_options_novel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
