# Generated by Django 5.0.3 on 2024-08-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_rename_translate_language_novel_translated_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('continues', 'Continues'), ('finished', 'Finished'), ('frozen', 'Frozen'), ('licensed', 'Licensed')], default='continues'),
        ),
    ]
