# Generated by Django 5.0.3 on 2024-07-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_delete_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
