# Generated by Django 5.0.3 on 2024-08-27 14:18

import apps.novels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_alter_novel_slug_alter_novel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='cover',
            field=models.ImageField(default='default_novel_cover.png', upload_to=apps.novels.models._get_image_save_path),
        ),
    ]
