# Generated by Django 5.0.3 on 2024-07-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_novel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbrevation', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
    ]
