# Generated by Django 5.0.3 on 2024-08-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_novel_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='original_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
