# Generated by Django 5.0.3 on 2024-07-16 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.RenameField(
            model_name='novel',
            old_name='description',
            new_name='synopsys',
        ),
        migrations.AddField(
            model_name='novel',
            name='languages',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='novels', to='novels.languages'),
        ),
        migrations.AddField(
            model_name='novel',
            name='original_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Continues'), (2, 'Finished'), (3, 'Frozen')], default=1),
        ),
        migrations.AddField(
            model_name='novel',
            name='translate_language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translated_novels', to='novels.languages'),
        ),
    ]
