# Generated by Django 5.0.3 on 2024-09-01 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
        ('novels', '0007_alter_novel_original_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='translated_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translated_novels', to='metadata.language'),
        ),
    ]
