# Generated by Django 5.0.3 on 2024-07-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_country_language_rename_description_novel_synopsys_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='languages',
            new_name='language',
        ),
    ]
