# Generated by Django 5.0.3 on 2024-09-11 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('comment_type', models.CharField(choices=[('novel', 'Novel'), ('chapter', 'Chapter')], max_length=10)),
                ('message', models.TextField()),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chapters.chapter')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
