# Generated by Django 5.0.3 on 2024-05-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_libraryitem_created_at_libraryitem_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryitem',
            options={'ordering': ['library', '-created_at']},
        ),
    ]
