# Generated by Django 5.0.3 on 2024-07-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_alter_libraryitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['user']},
        ),
    ]
